[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "openrouter"
version = "1.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Agent", "Model Provider", "Vendor/OpenRouter", "Area/AI & Machine Learning", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-openrouter"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
