// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# OpenAI-compatible API with additional OpenRouter features
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://openrouter.ai/api/v1") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Create a response
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful response 
    resource isolated function post responses(OpenResponsesRequest payload, CreateResponsesHeaders headers = {}) returns OpenResponsesNonStreamingResponse|error {
        string resourcePath = string `/responses`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Create a message
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful response 
    resource isolated function post messages(AnthropicMessagesRequest payload, CreateMessagesHeaders headers = {}) returns AnthropicMessagesResponse|error {
        string resourcePath = string `/messages`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get user activity grouped by endpoint
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns user activity data grouped by endpoint 
    resource isolated function get activity(GetUserActivityHeaders headers = {}, *GetUserActivityQueries queries) returns ActivityResponse|error {
        string resourcePath = string `/activity`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a chat completion
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful chat completion response 
    resource isolated function post chat/completions(ChatGenerationParams payload, SendChatCompletionRequestHeaders headers = {}) returns ChatResponse|error {
        string resourcePath = string `/chat/completions`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get remaining credits
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns the total credits purchased and used 
    resource isolated function get credits(GetCreditsHeaders headers = {}) returns CreditsResponse|error {
        string resourcePath = string `/credits`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a Coinbase charge for crypto payment
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns the calldata to fulfill the transaction 
    resource isolated function post credits/coinbase(CreateCoinbaseChargeHeaders headers = {}) returns CoinbaseCreditResponse|error {
        string resourcePath = string `/credits/coinbase`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Submit an embedding request
    #
    # + headers - Headers to be sent with the request 
    # + return - Embedding response 
    resource isolated function post embeddings(CreateEmbeddingsRequest payload, CreateEmbeddingsHeaders headers = {}) returns CreateEmbeddingsResponse|error {
        string resourcePath = string `/embeddings`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # List all embeddings models
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns a list of embeddings models 
    resource isolated function get embeddings/models(ListEmbeddingsModelsHeaders headers = {}) returns ModelsListResponse|error {
        string resourcePath = string `/embeddings/models`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get request & usage metadata for a generation
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns the request metadata for this generation 
    resource isolated function get generation(GetGenerationHeaders headers = {}, *GetGenerationQueries queries) returns GenerationResponse|error {
        string resourcePath = string `/generation`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get total count of available models
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns the total count of available models 
    resource isolated function get models/count(ListModelsCountHeaders headers = {}, *ListModelsCountQueries queries) returns ModelsCountResponse|error {
        string resourcePath = string `/models/count`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List all models and their properties
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Returns a list of models or RSS feed 
    resource isolated function get models(GetModelsHeaders headers = {}, *GetModelsQueries queries) returns ModelsListResponse|error {
        string resourcePath = string `/models`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List models filtered by user provider preferences, privacy settings, and guardrails
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns a list of models filtered by user provider preferences 
    resource isolated function get models/user(ListModelsUserHeaders headers = {}) returns ModelsListResponse|error {
        string resourcePath = string `/models/user`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List all endpoints for a model
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns a list of endpoints 
    resource isolated function get models/[string author]/[string slug]/endpoints(ListEndpointsHeaders headers = {}) returns ModelEndpointsResponse|error {
        string resourcePath = string `/models/${getEncodedUri(author)}/${getEncodedUri(slug)}/endpoints`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Preview the impact of ZDR on the available endpoints
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns a list of endpoints 
    resource isolated function get endpoints/zdr(ListEndpointsZdrHeaders headers = {}) returns ZdrEndpointsResponse|error {
        string resourcePath = string `/endpoints/zdr`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List all providers
    #
    # + headers - Headers to be sent with the request 
    # + return - Returns a list of providers 
    resource isolated function get providers(ListProvidersHeaders headers = {}) returns ProvidersResponse|error {
        string resourcePath = string `/providers`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List API keys
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of API keys 
    resource isolated function get keys(ListHeaders headers = {}, *ListQueries queries) returns KeysListResponse|error {
        string resourcePath = string `/keys`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a new API key
    #
    # + headers - Headers to be sent with the request 
    # + return - API key created successfully 
    resource isolated function post keys(CreateKeyRequest payload, CreateKeysHeaders headers = {}) returns CreateKeyResponse|error {
        string resourcePath = string `/keys`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get a single API key
    #
    # + hash - The hash identifier of the API key to retrieve
    # + headers - Headers to be sent with the request 
    # + return - API key details 
    resource isolated function get keys/[string hash](GetKeyHeaders headers = {}) returns KeyDetailsResponse|error {
        string resourcePath = string `/keys/${getEncodedUri(hash)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Delete an API key
    #
    # + hash - The hash identifier of the API key to delete
    # + headers - Headers to be sent with the request 
    # + return - API key deleted successfully 
    resource isolated function delete keys/[string hash](DeleteKeysHeaders headers = {}) returns DeleteKeyResponse|error {
        string resourcePath = string `/keys/${getEncodedUri(hash)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update an API key
    #
    # + hash - The hash identifier of the API key to update
    # + headers - Headers to be sent with the request 
    # + return - API key updated successfully 
    resource isolated function patch keys/[string hash](UpdateKeyRequest payload, UpdateKeysHeaders headers = {}) returns UpdateKeyResponse|error {
        string resourcePath = string `/keys/${getEncodedUri(hash)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # List guardrails
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of guardrails 
    resource isolated function get guardrails(ListGuardrailsHeaders headers = {}, *ListGuardrailsQueries queries) returns GuardrailListResponse|error {
        string resourcePath = string `/guardrails`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Create a guardrail
    #
    # + headers - Headers to be sent with the request 
    # + return - Guardrail created successfully 
    resource isolated function post guardrails(CreateGuardrailRequest payload, CreateGuardrailHeaders headers = {}) returns CreateGuardrailResponse|error {
        string resourcePath = string `/guardrails`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get a guardrail
    #
    # + id - The unique identifier of the guardrail to retrieve
    # + headers - Headers to be sent with the request 
    # + return - Guardrail details 
    resource isolated function get guardrails/[string id](GetGuardrailHeaders headers = {}) returns GetGuardrailResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Delete a guardrail
    #
    # + id - The unique identifier of the guardrail to delete
    # + headers - Headers to be sent with the request 
    # + return - Guardrail deleted successfully 
    resource isolated function delete guardrails/[string id](DeleteGuardrailHeaders headers = {}) returns DeleteGuardrailResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->delete(resourcePath, headers = httpHeaders);
    }

    # Update a guardrail
    #
    # + id - The unique identifier of the guardrail to update
    # + headers - Headers to be sent with the request 
    # + return - Guardrail updated successfully 
    resource isolated function patch guardrails/[string id](UpdateGuardrailRequest payload, UpdateGuardrailHeaders headers = {}) returns UpdateGuardrailResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->patch(resourcePath, request, httpHeaders);
    }

    # List all key assignments
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of key assignments 
    resource isolated function get guardrails/assignments/keys(ListKeyAssignmentsHeaders headers = {}, *ListKeyAssignmentsQueries queries) returns GuardrailKeyAssignmentsResponse|error {
        string resourcePath = string `/guardrails/assignments/keys`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List all member assignments
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of member assignments 
    resource isolated function get guardrails/assignments/members(ListMemberAssignmentsHeaders headers = {}, *ListMemberAssignmentsQueries queries) returns GuardrailMemberAssignmentsResponse|error {
        string resourcePath = string `/guardrails/assignments/members`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # List key assignments for a guardrail
    #
    # + id - The unique identifier of the guardrail
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of key assignments 
    resource isolated function get guardrails/[string id]/assignments/keys(ListGuardrailKeyAssignmentsHeaders headers = {}, *ListGuardrailKeyAssignmentsQueries queries) returns GuardrailKeyAssignmentsResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}/assignments/keys`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Bulk assign keys to a guardrail
    #
    # + id - The unique identifier of the guardrail
    # + headers - Headers to be sent with the request 
    # + return - Assignment result 
    resource isolated function post guardrails/[string id]/assignments/keys(AssignKeysRequest payload, BulkAssignKeysToGuardrailHeaders headers = {}) returns AssignKeysResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}/assignments/keys`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # List member assignments for a guardrail
    #
    # + id - The unique identifier of the guardrail
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - List of member assignments 
    resource isolated function get guardrails/[string id]/assignments/members(ListGuardrailMemberAssignmentsHeaders headers = {}, *ListGuardrailMemberAssignmentsQueries queries) returns GuardrailMemberAssignmentsResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}/assignments/members`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Bulk assign members to a guardrail
    #
    # + id - The unique identifier of the guardrail
    # + headers - Headers to be sent with the request 
    # + return - Assignment result 
    resource isolated function post guardrails/[string id]/assignments/members(AssignMembersRequest payload, BulkAssignMembersToGuardrailHeaders headers = {}) returns AssignMembersResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}/assignments/members`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Bulk unassign keys from a guardrail
    #
    # + id - The unique identifier of the guardrail
    # + headers - Headers to be sent with the request 
    # + return - Unassignment result 
    resource isolated function post guardrails/[string id]/assignments/keys/remove(RemoveKeysRequest payload, BulkUnassignKeysFromGuardrailHeaders headers = {}) returns RemoveKeysResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}/assignments/keys/remove`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Bulk unassign members from a guardrail
    #
    # + id - The unique identifier of the guardrail
    # + headers - Headers to be sent with the request 
    # + return - Unassignment result 
    resource isolated function post guardrails/[string id]/assignments/members/remove(RemoveMembersRequest payload, BulkUnassignMembersFromGuardrailHeaders headers = {}) returns RemoveMembersResponse|error {
        string resourcePath = string `/guardrails/${getEncodedUri(id)}/assignments/members/remove`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get current API key
    #
    # + headers - Headers to be sent with the request 
    # + return - API key details 
    resource isolated function get 'key(GetCurrentKeyHeaders headers = {}) returns CurrentKeyResponse|error {
        string resourcePath = string `/key`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Exchange authorization code for API key
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully exchanged code for an API key 
    resource isolated function post auth/keys(AuthKeyRequest payload, ExchangeAuthCodeForAPIKeyHeaders headers = {}) returns AuthKeyResponse|error {
        string resourcePath = string `/auth/keys`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Create authorization code
    #
    # + headers - Headers to be sent with the request 
    # + return - Successfully created authorization code 
    resource isolated function post auth/keys/code(KeyCodeRequest payload, CreateAuthKeysCodeHeaders headers = {}) returns KeyCodeResponse|error {
        string resourcePath = string `/auth/keys/code`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
